// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env.local first (higher priority), then .env as fallback
config({ path: ".env.local" });
config({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node ./node_modules/tsx/dist/cli.cjs prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
